import Navbar from "../components/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Main({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="">
        <Navbar/>
      {children}
    </div>
  );
}
